export const MESSAGE_TYPE = {
  CREATE_GAME: 'create_game',
  GAME_CREATED: 'game_created',
  GAME_JOINED: 'game_joined',
  GAME_FINISHED: 'game_finished',
  REG_USER: 'reg',
  JOIN_GAME: 'join_game',
  PLAYER_JOINED: 'player_joined',
  UPDATE_PLAYER: 'update_players',
  START_GAME: 'start_game',
  QUESTION: 'question',
  ANSWER: 'answer',
  ANSWER_ACCEPT: 'answer_accepted',
  RESULT: 'question_result',
} as const;
